name: Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,201,202,203,204,206,301,302,307,308,429
            --timeout 60
            --max-retries 3
            --exclude "example\\.com"
            --exclude "127\\.0\\.0\\.1"
            --exclude "localhost"
            --exclude "platform\\.openai\\.com"
            "topics/**/*.md"
            "engineering/**/*.md"
            "platforms/**/*.md"
            "_meta/**/*.md"
            "_templates/**/*.md"
            "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Link check summary
        if: always()
        run: echo "Link checking complete. Review results above."
