name: Markdown Lint

on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            **/*.md
            !node_modules/**

      - name: Lint summary
        if: always()
        run: echo "Markdown linting complete. Check output above for any issues."
